#!/usr/bin/env python3
import os
import sys

_lib = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
for _rel in (
    "python{}.{}".format(sys.version_info.major, sys.version_info.minor),
    "python3",
):
    _site = os.path.join(_lib, _rel, "site-packages")
    if os.path.isdir(_site):
        sys.path.insert(0, _site)
        break
    _dist = os.path.join(_lib, _rel, "dist-packages")
    if os.path.isdir(_dist):
        sys.path.insert(0, _dist)
        break

from bamboo_actuator_ros2.bamboo_actuator_node import main

if __name__ == "__main__":
    main()
